/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.text.DecimalFormat; //This will allow us to round to hundredths

/**
 *
 * @author Amy Zhang
 * Date: August 3rd, 2023
 * A GUI that calculates the tax, subtotal, and total of macaroons purchased by the user
 */
public class frmMakingPurchase extends javax.swing.JFrame {
    /**
     * Creates new form frmMakingPurchase
     */
    public frmMakingPurchase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblInstruction1 = new javax.swing.JLabel();
        lblInstruction2 = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        lblLemonPrice = new javax.swing.JLabel();
        lblBlueberryPrice = new javax.swing.JLabel();
        lblRaspberryPrice = new javax.swing.JLabel();
        lblBananaPrice = new javax.swing.JLabel();
        btnCalculateAll = new javax.swing.JButton();
        lblLimePrice = new javax.swing.JLabel();
        lblMacaroonPhoto = new javax.swing.JLabel();
        lblLemonOrdered = new javax.swing.JTextField();
        lblBlueberryOrdered = new javax.swing.JTextField();
        lblRaspberryOrdered = new javax.swing.JTextField();
        lblBananaOrdered = new javax.swing.JTextField();
        lblLimeOrdered = new javax.swing.JTextField();
        lblTaxOutput = new javax.swing.JLabel();
        lblSubtotalOutput = new javax.swing.JLabel();
        lblGrandTotalOutput = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        lblTitle.setText("Madeleine's Macaroons");

        lblInstruction1.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        lblInstruction1.setText("Enter the number of each macaroon that you would");

        lblInstruction2.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        lblInstruction2.setText("like to purchase and click Calculate");

        lblTax.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblTax.setText("Taxes (13%):");

        lblSubtotal.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblSubtotal.setText("Subtotal:");

        lblGrandTotal.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        lblGrandTotal.setText("Grand Total:");

        lblLemonPrice.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblLemonPrice.setText("Lemon Macaroons ($1.99):");

        lblBlueberryPrice.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblBlueberryPrice.setText("Blueberry Macaroons ($1.79):");

        lblRaspberryPrice.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblRaspberryPrice.setText("Raspberry Macaroons ($1.99):");

        lblBananaPrice.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblBananaPrice.setText("Banana Macaroons ($2.29):");

        btnCalculateAll.setBackground(new java.awt.Color(204, 204, 255));
        btnCalculateAll.setFont(new java.awt.Font("NSimSun", 1, 12)); // NOI18N
        btnCalculateAll.setText("Calculate");
        btnCalculateAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateAllActionPerformed(evt);
            }
        });

        lblLimePrice.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblLimePrice.setText("Lime Macaroons ($1.79):");

        lblMacaroonPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo_of_macaroons.PNG"))); // NOI18N
        lblMacaroonPhoto.setText("jLabel13");
        lblMacaroonPhoto.setMaximumSize(new java.awt.Dimension(1026, 541));
        lblMacaroonPhoto.setPreferredSize(new java.awt.Dimension(100, 100));

        lblLemonOrdered.setText("0");
        lblLemonOrdered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLemonOrderedActionPerformed(evt);
            }
        });

        lblBlueberryOrdered.setText("0");
        lblBlueberryOrdered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBlueberryOrderedActionPerformed(evt);
            }
        });

        lblRaspberryOrdered.setText("0");
        lblRaspberryOrdered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRaspberryOrderedActionPerformed(evt);
            }
        });

        lblBananaOrdered.setText("0");

        lblLimeOrdered.setText("0");

        lblTaxOutput.setText("$0.00");

        lblSubtotalOutput.setText("$0.00");

        lblGrandTotalOutput.setText("$0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMacaroonPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRaspberryPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLimePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBananaPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBlueberryPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLemonPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLemonOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBlueberryOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblRaspberryOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLimeOrdered, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblBananaOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstruction1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblTitle)))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(lblInstruction2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(btnCalculateAll))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTaxOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSubtotalOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblGrandTotalOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInstruction1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstruction2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMacaroonPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 23, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLemonPrice)
                            .addComponent(lblLemonOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBlueberryPrice)
                            .addComponent(lblBlueberryOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaspberryPrice)
                            .addComponent(lblRaspberryOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLimePrice)
                            .addComponent(lblLimeOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBananaOrdered)
                            .addComponent(lblBananaPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnCalculateAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTax)
                            .addComponent(lblTaxOutput))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubtotal)
                            .addComponent(lblSubtotalOutput))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrandTotal)
                            .addComponent(lblGrandTotalOutput))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateAllActionPerformed
        //Declaring the decimal format to be 2 decimal places
        DecimalFormat df2 = new DecimalFormat("0.00");
        
        //Declaring the prices of the 5 types of macaroons and storing them in appropriate variables
        final double DBLLEMONPRICE = 1.99, DBLBLUEBERRYPRICE = 1.79, DBLRASPBERRYPRICE = 1.99, DBLLIMEPRICE = 1.79, DBLBANANAPRICE = 2.29;
        //Declaring the tax and storing it in an appropriate variable
        final double DBLTAX = 0.13;
        
        //Variable to read purchase of lemon macaroons from the text field and converting into an integer 
        int intLemonOrdered = Integer.parseInt(lblLemonOrdered.getText());
        //Variable to read purchase of blueberry macaroons from the text field and converting into an integer 
        int intBlueberryOrdered = Integer.parseInt(lblBlueberryOrdered.getText());
        //Variable to read purchase of raspberry macaroons from the text field and converting into an integer 
        int intRaspberryOrdered = Integer.parseInt(lblRaspberryOrdered.getText());
        //Variable to read purchase of lime macaroons from the text field and converting into an integer 
        int intLimeOrdered = Integer.parseInt(lblLimeOrdered.getText());
        //Variable to read purchase of banana macaroons from the text field and converting into an integer 
        int intBananaOrdered = Integer.parseInt(lblBananaOrdered.getText());
        
        //Multiplying the price of each type of macaroon by the amount purchased and then adding them together to calculate the subtotal stored in a variable 
        double dblSubtotal = (DBLLEMONPRICE * intLemonOrdered) + (DBLBLUEBERRYPRICE * intBlueberryOrdered) + (DBLRASPBERRYPRICE * intRaspberryOrdered) + (DBLLIMEPRICE * intLimeOrdered) + (DBLBANANAPRICE * intBananaOrdered);
        //Multiplying the subtotal by the tax and storing it in an variable
        double dblTax = dblSubtotal * DBLTAX;
        //Adding the subtotal and tax together to get the grand total and storing it in a variable
        double dblGrandTotal = dblTax + dblSubtotal;
        
        //Displaying the subtotal in the lblSubtotalOutput label rounded to two decimal places
        lblSubtotalOutput.setText(String.valueOf("$"+ df2.format(dblSubtotal)));
        //Displaying the tax in the lblTaxOutput label rounded to two decimal places
        lblTaxOutput.setText(String.valueOf("$"+ df2.format(dblTax)));
        //Displaying the grand total in the lblGrandTotalOutput label rounded to two decimal places
        lblGrandTotalOutput.setText(String.valueOf("$"+ df2.format(dblGrandTotal)));
    }//GEN-LAST:event_btnCalculateAllActionPerformed

    private void lblLemonOrderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLemonOrderedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLemonOrderedActionPerformed

    private void lblBlueberryOrderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBlueberryOrderedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBlueberryOrderedActionPerformed

    private void lblRaspberryOrderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRaspberryOrderedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRaspberryOrderedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMakingPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMakingPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMakingPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMakingPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMakingPurchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateAll;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lblBananaOrdered;
    private javax.swing.JLabel lblBananaPrice;
    private javax.swing.JTextField lblBlueberryOrdered;
    private javax.swing.JLabel lblBlueberryPrice;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblGrandTotalOutput;
    private javax.swing.JLabel lblInstruction1;
    private javax.swing.JLabel lblInstruction2;
    private javax.swing.JTextField lblLemonOrdered;
    private javax.swing.JLabel lblLemonPrice;
    private javax.swing.JTextField lblLimeOrdered;
    private javax.swing.JLabel lblLimePrice;
    private javax.swing.JLabel lblMacaroonPhoto;
    private javax.swing.JTextField lblRaspberryOrdered;
    private javax.swing.JLabel lblRaspberryPrice;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalOutput;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTaxOutput;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
